spring:
  application:
    name: Runner
  datasource:
    url: jdbc:postgresql://localhost:5432/rungroop
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update